#!/usr/bin/env bash
set -e

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${BASE_DIR}/.." && pwd)"
CERTS_DIR="${REPO_ROOT}/certs"

echo "🔎 Checking write permissions on repository root..."

if ! touch "${REPO_ROOT}/.write-test" 2>/dev/null; then
  echo "❌ ERROR: Repository directory is not writable:"
  echo "   ${REPO_ROOT}"
  exit 1
fi
rm -f "${REPO_ROOT}/.write-test"

echo "✅ Repository is writable"

echo "📁 Creating certificate directories..."
mkdir -p \
  "${CERTS_DIR}/ca" \
  "${CERTS_DIR}/opensearch" \
  "${CERTS_DIR}/dashboards" \
  "${CERTS_DIR}/dataprepper" \
  "${CERTS_DIR}/admin"

echo "🔐 Generating internal CA..."

openssl genrsa -out "${CERTS_DIR}/ca/ca.key" 4096

openssl req -x509 -new -nodes \
  -key "${CERTS_DIR}/ca/ca.key" \
  -sha256 -days 3650 \
  -out "${CERTS_DIR}/ca/ca.crt" \
  -subj "/C=FR/ST=IDF/L=Paris/O=NDR/CN=ndr-internal-ca"

generate_cert () {
  NAME=$1
  CN=$2
  DNS=$3
  EKU=$4

  echo "🔐 Generating certificate for ${NAME}..."

  openssl genrsa -out "${CERTS_DIR}/${NAME}/${NAME}.key" 4096

  openssl req -new \
    -key "${CERTS_DIR}/${NAME}/${NAME}.key" \
    -out "${CERTS_DIR}/${NAME}/${NAME}.csr" \
    -subj "/C=FR/ST=IDF/L=Paris/O=NDR/CN=${CN}"

  cat > "${CERTS_DIR}/${NAME}/${NAME}.ext" <<EOF
subjectAltName = DNS:${DNS},DNS:localhost,IP:127.0.0.1
extendedKeyUsage = ${EKU}
EOF

  openssl x509 -req \
    -in "${CERTS_DIR}/${NAME}/${NAME}.csr" \
    -CA "${CERTS_DIR}/ca/ca.crt" \
    -CAkey "${CERTS_DIR}/ca/ca.key" \
    -CAcreateserial \
    -out "${CERTS_DIR}/${NAME}/${NAME}.crt" \
    -days 825 -sha256 \
    -extfile "${CERTS_DIR}/${NAME}/${NAME}.ext"

  rm -f \
    "${CERTS_DIR}/${NAME}/${NAME}.csr" \
    "${CERTS_DIR}/${NAME}/${NAME}.ext"
}

# Server certificates
generate_cert "opensearch" "opensearch-node1" "opensearch-node1" "serverAuth, clientAuth"
generate_cert "dashboards" "opensearch-dashboards" "opensearch-dashboards" "serverAuth, clientAuth"
generate_cert "dataprepper" "dataprepper" "dataprepper" "serverAuth, clientAuth"

# 🔐 Admin client certificate (clientAuth only)
generate_cert "admin" "admin" "admin" "clientAuth"

cat > "${CERTS_DIR}/README.txt" <<EOF
Generated by generate-certs.sh

- Internal self-signed CA
- PEM format
- SAN-enabled certificates
- Includes admin client certificate
- Docker-compatible permissions
- Non-root container friendly

Do NOT commit private keys to public repositories.
EOF

echo "🔒 Applying reproducible permissions..."

find "${CERTS_DIR}" -type d -exec chmod 755 {} \;
find "${CERTS_DIR}" -name "*.key" -exec chmod 644 {} \;
find "${CERTS_DIR}" -name "*.crt" -exec chmod 644 {} \;
chmod 644 "${CERTS_DIR}/README.txt"

echo "✅ Certificate generation completed successfully"
